
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 07 19:53:05 CST 2020
//----------------------------------------------------

package gramaticas;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AGRUPACION_A = 6;
  public static final int acumular = 18;
  public static final int mostrarNaves = 20;
  public static final int ENTERO = 35;
  public static final int planetas = 30;
  public static final int produccion = 22;
  public static final int FACIL = 34;
  public static final int PLANETAS = 24;
  public static final int size = 14;
  public static final int DOS_PUNTOS = 8;
  public static final int alAzar = 15;
  public static final int finalizacion = 23;
  public static final int LLAVE_B = 5;
  public static final int NEUTRALES = 19;
  public static final int LLAVE_A = 4;
  public static final int DIFICIL = 33;
  public static final int mostrarEstadisticas = 21;
  public static final int MAPA = 12;
  public static final int porcMuertes = 27;
  public static final int ID = 37;
  public static final int DECIMAL = 36;
  public static final int EOF = 0;
  public static final int pNeutrales = 16;
  public static final int COMILLAS = 11;
  public static final int nombre = 25;
  public static final int error = 1;
  public static final int color = 40;
  public static final int COMA = 9;
  public static final int PLANETAS_NEUTRALES = 28;
  public static final int COLOR = 43;
  public static final int posY = 42;
  public static final int mapaCiego = 17;
  public static final int posX = 41;
  public static final int HUMANO = 32;
  public static final int id = 13;
  public static final int PUNTO = 10;
  public static final int tipo = 31;
  public static final int FALSO = 3;
  public static final int filas = 38;
  public static final int JUGADORES = 29;
  public static final int columnas = 39;
  public static final int naves = 26;
  public static final int VERDADERO = 2;
  public static final int AGRUPACION_B = 7;
}

