
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 30 22:56:29 CST 2020
//----------------------------------------------------

package gramaticas4;

import java_cup.runtime.Symbol;
import Pollitos.NavesCamino;
import Pollitos.ResumenTurno;
import Pollitos.DatosAcciones;
import javax.swing.JTextArea;
import interfaz.VentanaPrincipal;
import Pollitos.Turnos;
import Pollitos.AccionesOnline;
import java.util.ArrayList;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Mon Mar 30 22:56:29 CST 2020
  */
public class SintaxOnline extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public SintaxOnline() {super();}

  /** Constructor which sets the default scanner. */
  public SintaxOnline(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public SintaxOnline(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\071\000\002\002\004\000\002\002\003\000\002\003" +
    "\006\000\002\046\004\000\002\046\004\000\002\046\004" +
    "\000\002\046\002\000\002\046\004\000\002\047\004\000" +
    "\002\047\004\000\002\047\004\000\002\021\006\000\002" +
    "\021\005\000\002\020\010\000\002\020\007\000\002\017" +
    "\007\000\002\017\006\000\002\004\004\000\002\004\004" +
    "\000\002\004\004\000\002\004\004\000\002\004\004\000" +
    "\002\004\004\000\002\004\004\000\002\004\004\000\002" +
    "\004\004\000\002\004\004\000\002\004\002\000\002\004" +
    "\004\000\002\005\004\000\002\005\004\000\002\005\004" +
    "\000\002\005\004\000\002\005\004\000\002\005\004\000" +
    "\002\005\004\000\002\005\004\000\002\005\004\000\002" +
    "\005\004\000\002\006\005\000\002\007\005\000\002\010" +
    "\005\000\002\011\005\000\002\012\005\000\002\013\005" +
    "\000\002\014\005\000\002\015\005\000\002\016\005\000" +
    "\002\016\005\000\002\030\006\000\002\031\004\000\002" +
    "\031\004\000\002\031\002\000\002\032\004\000\002\027" +
    "\006\000\002\027\006\000\002\027\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\175\000\004\056\005\001\002\000\004\002\000\001" +
    "\002\000\004\006\010\001\002\000\004\002\007\001\002" +
    "\000\004\002\001\001\002\000\014\003\014\007\ufffb\013" +
    "\011\060\016\101\013\001\002\000\010\003\171\060\016" +
    "\101\013\001\002\000\004\007\170\001\002\000\004\006" +
    "\150\001\002\000\014\003\014\007\ufffb\013\011\060\016" +
    "\101\013\001\002\000\014\003\014\007\ufffb\013\011\060" +
    "\016\101\013\001\002\000\004\006\021\001\002\000\014" +
    "\003\014\007\ufffb\013\011\060\016\101\013\001\002\000" +
    "\004\007\ufffe\001\002\000\006\007\024\047\022\001\002" +
    "\000\004\012\026\001\002\000\004\007\025\001\002\000" +
    "\014\003\ufff5\007\ufff5\013\ufff5\060\ufff5\101\ufff5\001\002" +
    "\000\014\003\ufff6\007\ufff6\013\ufff6\060\ufff6\101\ufff6\001" +
    "\002\000\004\010\027\001\002\000\004\061\031\001\002" +
    "\000\004\011\144\001\002\000\004\010\032\001\002\000" +
    "\032\003\054\011\uffe6\013\044\035\042\062\056\063\047" +
    "\064\055\065\035\066\057\070\034\071\053\077\033\001" +
    "\002\000\004\012\142\001\002\000\004\012\140\001\002" +
    "\000\004\012\136\001\002\000\032\003\054\011\uffe6\013" +
    "\044\035\042\062\056\063\047\064\055\065\035\066\057" +
    "\070\034\071\053\077\033\001\002\000\032\003\054\011" +
    "\uffe6\013\044\035\042\062\056\063\047\064\055\065\035" +
    "\066\057\070\034\071\053\077\033\001\002\000\032\003" +
    "\054\011\uffe6\013\044\035\042\062\056\063\047\064\055" +
    "\065\035\066\057\070\034\071\053\077\033\001\002\000" +
    "\032\003\054\011\uffe6\013\044\035\042\062\056\063\047" +
    "\064\055\065\035\066\057\070\034\071\053\077\033\001" +
    "\002\000\004\012\130\001\002\000\032\003\054\011\uffe6" +
    "\013\044\035\042\062\056\063\047\064\055\065\035\066" +
    "\057\070\034\071\053\077\033\001\002\000\026\003\114" +
    "\035\042\062\056\063\047\064\055\065\035\066\057\070" +
    "\034\071\053\077\033\001\002\000\032\003\054\011\uffe6" +
    "\013\044\035\042\062\056\063\047\064\055\065\035\066" +
    "\057\070\034\071\053\077\033\001\002\000\032\003\054" +
    "\011\uffe6\013\044\035\042\062\056\063\047\064\055\065" +
    "\035\066\057\070\034\071\053\077\033\001\002\000\004" +
    "\012\076\001\002\000\032\003\054\011\uffe6\013\044\035" +
    "\042\062\056\063\047\064\055\065\035\066\057\070\034" +
    "\071\053\077\033\001\002\000\032\003\054\011\uffe6\013" +
    "\044\035\042\062\056\063\047\064\055\065\035\066\057" +
    "\070\034\071\053\077\033\001\002\000\004\011\072\001" +
    "\002\000\004\012\067\001\002\000\032\003\054\011\uffe6" +
    "\013\044\035\042\062\056\063\047\064\055\065\035\066" +
    "\057\070\034\071\053\077\033\001\002\000\004\012\064" +
    "\001\002\000\004\012\062\001\002\000\004\012\060\001" +
    "\002\000\004\045\061\001\002\000\032\003\uffd5\011\uffd5" +
    "\013\uffd5\035\uffd5\062\uffd5\063\uffd5\064\uffd5\065\uffd5\066" +
    "\uffd5\070\uffd5\071\uffd5\077\uffd5\001\002\000\004\047\063" +
    "\001\002\000\032\003\uffd9\011\uffd9\013\uffd9\035\uffd9\062" +
    "\uffd9\063\uffd9\064\uffd9\065\uffd9\066\uffd9\070\uffd9\071\uffd9" +
    "\077\uffd9\001\002\000\004\045\065\001\002\000\032\003" +
    "\uffd7\011\uffd7\013\uffd7\035\uffd7\062\uffd7\063\uffd7\064\uffd7" +
    "\065\uffd7\066\uffd7\070\uffd7\071\uffd7\077\uffd7\001\002\000" +
    "\004\011\uffe5\001\002\000\006\004\071\005\070\001\002" +
    "\000\032\003\uffd1\011\uffd1\013\uffd1\035\uffd1\062\uffd1\063" +
    "\uffd1\064\uffd1\065\uffd1\066\uffd1\070\uffd1\071\uffd1\077\uffd1" +
    "\001\002\000\032\003\uffd2\011\uffd2\013\uffd2\035\uffd2\062" +
    "\uffd2\063\uffd2\064\uffd2\065\uffd2\066\uffd2\070\uffd2\071\uffd2" +
    "\077\uffd2\001\002\000\006\011\ufff1\061\031\001\002\000" +
    "\004\011\ufff2\001\002\000\004\011\ufff0\001\002\000\004" +
    "\011\uffef\001\002\000\004\047\077\001\002\000\032\003" +
    "\uffd8\011\uffd8\013\uffd8\035\uffd8\062\uffd8\063\uffd8\064\uffd8" +
    "\065\uffd8\066\uffd8\070\uffd8\071\uffd8\077\uffd8\001\002\000" +
    "\004\011\uffee\001\002\000\004\011\uffed\001\002\000\004" +
    "\011\uffe7\001\002\000\032\003\054\011\uffe6\013\044\035" +
    "\042\062\056\063\047\064\055\065\035\066\057\070\034" +
    "\071\053\077\033\001\002\000\032\003\054\011\uffe6\013" +
    "\044\035\042\062\056\063\047\064\055\065\035\066\057" +
    "\070\034\071\053\077\033\001\002\000\032\003\054\011" +
    "\uffe6\013\044\035\042\062\056\063\047\064\055\065\035" +
    "\066\057\070\034\071\053\077\033\001\002\000\032\003" +
    "\054\011\uffe6\013\044\035\042\062\056\063\047\064\055" +
    "\065\035\066\057\070\034\071\053\077\033\001\002\000" +
    "\032\003\054\011\uffe6\013\044\035\042\062\056\063\047" +
    "\064\055\065\035\066\057\070\034\071\053\077\033\001" +
    "\002\000\032\003\054\011\uffe6\013\044\035\042\062\056" +
    "\063\047\064\055\065\035\066\057\070\034\071\053\077" +
    "\033\001\002\000\032\003\054\011\uffe6\013\044\035\042" +
    "\062\056\063\047\064\055\065\035\066\057\070\034\071" +
    "\053\077\033\001\002\000\032\003\054\011\uffe6\013\044" +
    "\035\042\062\056\063\047\064\055\065\035\066\057\070" +
    "\034\071\053\077\033\001\002\000\032\003\054\011\uffe6" +
    "\013\044\035\042\062\056\063\047\064\055\065\035\066" +
    "\057\070\034\071\053\077\033\001\002\000\032\003\054" +
    "\011\uffe6\013\044\035\042\062\056\063\047\064\055\065" +
    "\035\066\057\070\034\071\053\077\033\001\002\000\004" +
    "\011\uffdb\001\002\000\004\011\uffe4\001\002\000\004\011" +
    "\uffe3\001\002\000\004\011\uffe2\001\002\000\004\011\uffe1" +
    "\001\002\000\004\011\uffe0\001\002\000\004\011\uffdf\001" +
    "\002\000\004\011\uffde\001\002\000\004\011\uffdd\001\002" +
    "\000\004\011\uffdc\001\002\000\004\011\uffec\001\002\000" +
    "\004\046\131\001\002\000\032\003\uffd4\011\uffd4\013\uffd4" +
    "\035\uffd4\062\uffd4\063\uffd4\064\uffd4\065\uffd4\066\uffd4\070" +
    "\uffd4\071\uffd4\077\uffd4\001\002\000\004\011\uffeb\001\002" +
    "\000\004\011\uffea\001\002\000\004\011\uffe9\001\002\000" +
    "\004\011\uffe8\001\002\000\004\045\137\001\002\000\032" +
    "\003\uffd6\011\uffd6\013\uffd6\035\uffd6\062\uffd6\063\uffd6\064" +
    "\uffd6\065\uffd6\066\uffd6\070\uffd6\071\uffd6\077\uffd6\001\002" +
    "\000\004\045\141\001\002\000\032\003\uffd3\011\uffd3\013" +
    "\uffd3\035\uffd3\062\uffd3\063\uffd3\064\uffd3\065\uffd3\066\uffd3" +
    "\070\uffd3\071\uffd3\077\uffd3\001\002\000\004\045\143\001" +
    "\002\000\032\003\uffda\011\uffda\013\uffda\035\uffda\062\uffda" +
    "\063\uffda\064\uffda\065\uffda\066\uffda\070\uffda\071\uffda\077" +
    "\uffda\001\002\000\006\007\ufff3\047\022\001\002\000\004" +
    "\007\ufff4\001\002\000\004\007\ufffd\001\002\000\004\007" +
    "\ufffa\001\002\000\012\003\152\007\uffcd\013\151\074\155" +
    "\001\002\000\006\003\152\074\155\001\002\000\006\003" +
    "\152\074\155\001\002\000\012\003\152\007\uffcd\013\151" +
    "\074\155\001\002\000\004\007\162\001\002\000\004\047" +
    "\156\001\002\000\004\012\157\001\002\000\006\004\161" +
    "\005\160\001\002\000\012\003\uffca\007\uffca\013\uffca\074" +
    "\uffca\001\002\000\012\003\uffcb\007\uffcb\013\uffcb\074\uffcb" +
    "\001\002\000\014\003\uffd0\007\uffd0\013\uffd0\060\uffd0\101" +
    "\uffd0\001\002\000\004\007\uffcf\001\002\000\012\003\uffc9" +
    "\007\uffc9\013\uffc9\074\uffc9\001\002\000\004\007\uffce\001" +
    "\002\000\012\003\152\007\uffcd\013\151\074\155\001\002" +
    "\000\004\007\uffcc\001\002\000\004\002\uffff\001\002\000" +
    "\014\003\014\007\ufffb\013\011\060\016\101\013\001\002" +
    "\000\004\007\ufffc\001\002\000\014\003\014\007\ufffb\013" +
    "\011\060\016\101\013\001\002\000\014\003\014\007\ufffb" +
    "\013\011\060\016\101\013\001\002\000\004\007\ufff9\001" +
    "\002\000\004\007\ufff8\001\002\000\004\007\ufff7\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\175\000\006\002\005\003\003\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\021\016\030\014\046\011\001\001\000\010\021" +
    "\173\030\172\047\171\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\021\016\030\014\046\146\001\001\000" +
    "\010\021\016\030\014\046\145\001\001\000\002\001\001" +
    "\000\010\021\016\030\014\046\017\001\001\000\002\001" +
    "\001\000\004\020\022\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\017\027\001\001\000\002\001\001\000\002" +
    "\001\001\000\026\004\051\006\050\007\047\010\045\011" +
    "\044\012\042\013\040\014\037\015\036\016\035\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\026\004\134\006\050\007\047\010\045\011\044\012\042" +
    "\013\040\014\037\015\036\016\035\001\001\000\026\004" +
    "\133\006\050\007\047\010\045\011\044\012\042\013\040" +
    "\014\037\015\036\016\035\001\001\000\026\004\132\006" +
    "\050\007\047\010\045\011\044\012\042\013\040\014\037" +
    "\015\036\016\035\001\001\000\026\004\131\006\050\007" +
    "\047\010\045\011\044\012\042\013\040\014\037\015\036" +
    "\016\035\001\001\000\002\001\001\000\026\004\126\006" +
    "\050\007\047\010\045\011\044\012\042\013\040\014\037" +
    "\015\036\016\035\001\001\000\026\005\101\006\112\007" +
    "\111\010\110\011\107\012\106\013\105\014\104\015\103" +
    "\016\102\001\001\000\026\004\100\006\050\007\047\010" +
    "\045\011\044\012\042\013\040\014\037\015\036\016\035" +
    "\001\001\000\026\004\077\006\050\007\047\010\045\011" +
    "\044\012\042\013\040\014\037\015\036\016\035\001\001" +
    "\000\002\001\001\000\026\004\074\006\050\007\047\010" +
    "\045\011\044\012\042\013\040\014\037\015\036\016\035" +
    "\001\001\000\026\004\073\006\050\007\047\010\045\011" +
    "\044\012\042\013\040\014\037\015\036\016\035\001\001" +
    "\000\002\001\001\000\002\001\001\000\026\004\065\006" +
    "\050\007\047\010\045\011\044\012\042\013\040\014\037" +
    "\015\036\016\035\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\017\072\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\026\004\125\006\050\007\047" +
    "\010\045\011\044\012\042\013\040\014\037\015\036\016" +
    "\035\001\001\000\026\004\124\006\050\007\047\010\045" +
    "\011\044\012\042\013\040\014\037\015\036\016\035\001" +
    "\001\000\026\004\123\006\050\007\047\010\045\011\044" +
    "\012\042\013\040\014\037\015\036\016\035\001\001\000" +
    "\026\004\122\006\050\007\047\010\045\011\044\012\042" +
    "\013\040\014\037\015\036\016\035\001\001\000\026\004" +
    "\121\006\050\007\047\010\045\011\044\012\042\013\040" +
    "\014\037\015\036\016\035\001\001\000\026\004\120\006" +
    "\050\007\047\010\045\011\044\012\042\013\040\014\037" +
    "\015\036\016\035\001\001\000\026\004\117\006\050\007" +
    "\047\010\045\011\044\012\042\013\040\014\037\015\036" +
    "\016\035\001\001\000\026\004\116\006\050\007\047\010" +
    "\045\011\044\012\042\013\040\014\037\015\036\016\035" +
    "\001\001\000\026\004\115\006\050\007\047\010\045\011" +
    "\044\012\042\013\040\014\037\015\036\016\035\001\001" +
    "\000\026\004\114\006\050\007\047\010\045\011\044\012" +
    "\042\013\040\014\037\015\036\016\035\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\020\144\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\027\152\031\153\001\001\000" +
    "\006\027\165\032\164\001\001\000\004\027\163\001\001" +
    "\000\006\027\152\031\162\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\027\152" +
    "\031\166\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\021\016\030\014\046\176\001\001\000\002\001\001" +
    "\000\010\021\016\030\014\046\175\001\001\000\010\021" +
    "\016\030\014\046\174\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$SintaxOnline$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$SintaxOnline$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$SintaxOnline$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    public AccionesOnline online;
    public static String totalErrores;
    public JTextArea panelMensajes;
    public ArrayList<AccionesOnline> listOnline;

   public SintaxOnline(AnalizadorLexico4 lex, JTextArea panelMensajes, ArrayList<AccionesOnline> listOnline){
        super(lex);
        this.online = online;
        this.panelMensajes = panelMensajes;
        this.listOnline = listOnline;
        
    }

    public void setAccion(String tipo, String mensaje, String accion){
        System.out.println(tipo+" "+mensaje);
    }
  
    public void syntax_error(Symbol s){
        setAccion("ERROR", "Error sintaxis columna: "+s.right+" fila: "+s.left,"");
        totalErrores += "ERROR: Error sintaxis columna: "+s.right+" fila: "+s.left+"\n";
        panelMensajes.setText(totalErrores);
    }


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$SintaxOnline$actions {
  private final SintaxOnline parser;

  /** Constructor */
  CUP$SintaxOnline$actions(SintaxOnline parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$SintaxOnline$do_action(
    int                        CUP$SintaxOnline$act_num,
    java_cup.runtime.lr_parser CUP$SintaxOnline$parser,
    java.util.Stack            CUP$SintaxOnline$stack,
    int                        CUP$SintaxOnline$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$SintaxOnline$result;

      /* select the action based on the action number */
      switch (CUP$SintaxOnline$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // e2 ::= error e2 
            {
              ResumenTurno RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		ResumenTurno e = (ResumenTurno)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 parser.totalErrores += "Atributo en campo RESUMEN sentenciado de forma incorrecta.\n"; e.setTodoCorrecto(false); RESULT=e; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("e2",21, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // e2 ::= estado ID DOS_PUNTOS FALSO 
            {
              ResumenTurno RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-2)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 ResumenTurno resumen = new ResumenTurno(); resumen.setNombreJugador(a.toString()); resumen.setEstadoJugador(Boolean.valueOf(a.toString())); RESULT=resumen; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("e2",21, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-3)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // e2 ::= estado ID DOS_PUNTOS VERDADERO 
            {
              ResumenTurno RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-2)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 ResumenTurno resumen = new ResumenTurno(); resumen.setNombreJugador(b.toString()); resumen.setEstadoJugador(Boolean.valueOf(a.toString())); RESULT=resumen; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("e2",21, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-3)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // p3 ::= e2 e1 
            {
              ArrayList<ResumenTurno> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).right;
		ResumenTurno a = (ResumenTurno)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		ArrayList<ResumenTurno> e = (ArrayList<ResumenTurno>)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 if(e!=null){ if(a.getTodoCorrecto() == false){ RESULT=null; } else { e.add(a); RESULT=e; } } else { RESULT=null; } 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("p3",24, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // e1 ::= 
            {
              ArrayList<ResumenTurno> RESULT =null;
		 RESULT=new ArrayList<>(); 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("e1",23, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // e1 ::= COMA p3 
            {
              ArrayList<ResumenTurno> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		ArrayList<ResumenTurno> a = (ArrayList<ResumenTurno>)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 RESULT=a; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("e1",23, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // e1 ::= e2 e1 
            {
              ArrayList<ResumenTurno> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).right;
		ResumenTurno a = (ResumenTurno)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		ArrayList<ResumenTurno> e = (ArrayList<ResumenTurno>)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		  if(e!=null){ if(a.getTodoCorrecto() == null){ RESULT=null; } else {  e.add(a); RESULT=e; } } else { RESULT=null; } 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("e1",23, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // e ::= RESUMEN LLAVE_A e1 LLAVE_B 
            {
              ArrayList<ResumenTurno> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).right;
		ArrayList<ResumenTurno> a = (ArrayList<ResumenTurno>)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).value;
		 RESULT=a; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("e",22, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-3)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // c12 ::= verificador DOS_PUNTOS FALSO 
            {
              NavesCamino RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 NavesCamino naves = new NavesCamino(); naves.setVerificador(false); RESULT=naves; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("c12",12, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-2)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // c12 ::= verificador DOS_PUNTOS VERDADERO 
            {
              NavesCamino RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 NavesCamino naves = new NavesCamino(); naves.setVerificador(false); RESULT=naves; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("c12",12, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-2)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // c11 ::= turnoLlegada DOS_PUNTOS ENTERO 
            {
              NavesCamino RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 NavesCamino naves = new NavesCamino(); naves.setTurnoLlegada((Integer) a); RESULT=naves; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("c11",11, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-2)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // c10 ::= porcMuertes DOS_PUNTOS DECIMAL 
            {
              NavesCamino RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 NavesCamino naves = new NavesCamino(); naves.setPorcentajeMuertes(Float.parseFloat(a.toString())); RESULT=naves; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("c10",10, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-2)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // c9 ::= noJugadorAtaque DOS_PUNTOS ENTERO 
            {
              NavesCamino RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 NavesCamino naves = new NavesCamino(); naves.setNoJugadorAtaque((Integer) a ); RESULT=naves; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("c9",9, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-2)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // c8 ::= noJugadorEnvio DOS_PUNTOS ENTERO 
            {
              NavesCamino RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 NavesCamino naves = new NavesCamino(); naves.setNoJugadorEnvio((Integer) a); RESULT=naves; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("c8",8, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-2)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // c7 ::= noNaves DOS_PUNTOS ENTERO 
            {
              NavesCamino RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 NavesCamino naves = new NavesCamino(); naves.setNoNaves((Integer) a); RESULT=naves; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("c7",7, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-2)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // c6 ::= planetaDestino DOS_PUNTOS ID 
            {
              NavesCamino RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 NavesCamino naves = new NavesCamino(); naves.setPlanetaDestino(a.toString()); RESULT=naves; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("c6",6, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-2)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // c5 ::= planetaOrigen DOS_PUNTOS ID 
            {
              NavesCamino RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		  NavesCamino naves = new NavesCamino(); naves.setPlanetaOrigen(a.toString()); RESULT=naves; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("c5",5, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-2)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // c4 ::= noFlota DOS_PUNTOS ENTERO 
            {
              NavesCamino RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 NavesCamino naves = new NavesCamino(); naves.setNoFlota((Integer) a); RESULT=naves; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("c4",4, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-2)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // p1 ::= error c3 
            {
              NavesCamino RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		NavesCamino e = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 parser.totalErrores += "Atributo en campo FLOTA sentenciado de forma incorrecta.\n"; e.setTodoCorrecto(false); RESULT=e; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("p1",3, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // p1 ::= c12 c3 
            {
              NavesCamino RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).right;
		NavesCamino a = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		NavesCamino e = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 if(e!=null){ if(e.getVerificador()==null){ e.setVerificador(a.getVerificador()); } else { parser.totalErrores += "Sub-atributo verificador en campo FLOTA sentenciado mas de una vez. Linea: "+aleft+" Columna: "+aright+".\n"; e.setTodoCorrecto(false); } } RESULT=e; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("p1",3, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // p1 ::= c11 c3 
            {
              NavesCamino RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).right;
		NavesCamino a = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		NavesCamino e = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 if(e!=null){ if(e.getTurnoLlegada()==null){ e.setTurnoLlegada(a.getTurnoLlegada()); } else { parser.totalErrores += "Sub-atributo turnoLlegada en campo FLOTA sentenciado mas de una vez. Linea: "+aleft+" Columna: "+aright+".\n"; e.setTodoCorrecto(false); } } RESULT=e; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("p1",3, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // p1 ::= c10 c3 
            {
              NavesCamino RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).right;
		NavesCamino a = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		NavesCamino e = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 if(e!=null){ if(e.getPorcentajeMuertes()==null){ e.setPorcentajeMuertes(a.getPorcentajeMuertes()); } else { parser.totalErrores += "Sub-atributo porcentajeMuertes en campo FLOTA sentenciado mas de una vez. Linea: "+aleft+" Columna: "+aright+".\n"; e.setTodoCorrecto(false); } } RESULT=e; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("p1",3, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // p1 ::= c9 c3 
            {
              NavesCamino RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).right;
		NavesCamino a = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		NavesCamino e = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 if(e!=null){ if(e.getNoJugadorAtaque()==null){ e.setNoJugadorAtaque(a.getNoJugadorAtaque()); } else { parser.totalErrores += "Sub-atributo noJugadorAtaque en campo FLOTA sentenciado mas de una vez. Linea: "+aleft+" Columna: "+aright+".\n"; e.setTodoCorrecto(false); } } RESULT=e; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("p1",3, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // p1 ::= c8 c3 
            {
              NavesCamino RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).right;
		NavesCamino a = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		NavesCamino e = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 if(e!=null){ if(e.getNoJugadorEnvio()==null){ e.setNoJugadorEnvio(a.getNoJugadorEnvio()); } else { parser.totalErrores += "Sub-atributo noJugadorEnvio en campo FLOTA sentenciado mas de una vez. Linea: "+aleft+" Columna: "+aright+".\n"; e.setTodoCorrecto(false); } } RESULT=e; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("p1",3, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // p1 ::= c7 c3 
            {
              NavesCamino RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).right;
		NavesCamino a = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		NavesCamino e = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 if(e!=null){ if(e.getNoNaves()==null){ e.setNoNaves(a.getNoNaves()); } else { parser.totalErrores += "Sub-atributo noNaves en campo FLOTA sentenciado mas de una vez. Linea: "+aleft+" Columna: "+aright+".\n"; e.setTodoCorrecto(false); } } RESULT=e; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("p1",3, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // p1 ::= c6 c3 
            {
              NavesCamino RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).right;
		NavesCamino a = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		NavesCamino e = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 if(e!=null){ if(e.getPlanetaDestino()==null){ e.setPlanetaDestino(a.getPlanetaDestino()); } else { parser.totalErrores += "Sub-atributo planetaDestino en campo FLOTA sentenciado mas de una vez. Linea: "+aleft+" Columna: "+aright+".\n"; e.setTodoCorrecto(false); } } RESULT=e; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("p1",3, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // p1 ::= c5 c3 
            {
              NavesCamino RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).right;
		NavesCamino a = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		NavesCamino e = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 if(e!=null){ if(e.getPlanetaOrigen()==null){ e.setPlanetaOrigen(a.getPlanetaOrigen()); } else { parser.totalErrores += "Sub-atributo planetaOrigen en campo FLOTA sentenciado mas de una vez. Linea: "+aleft+" Columna: "+aright+".\n"; e.setTodoCorrecto(false); } } RESULT=e; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("p1",3, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // p1 ::= c4 c3 
            {
              NavesCamino RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).right;
		NavesCamino a = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		NavesCamino e = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 if(e!=null){ if(e.getNoFlota()==null){ e.setNoFlota(a.getNoFlota()); } else { parser.totalErrores += "Sub-atributo noFlota en campo FLOTA sentenciado mas de una vez. Linea: "+aleft+" Columna: "+aright+".\n"; e.setTodoCorrecto(false); } } RESULT=e; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("p1",3, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // c3 ::= error c3 
            {
              NavesCamino RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		NavesCamino e = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 parser.totalErrores += "Atributo en campo FLOTA sentenciado de forma incorrecta.\n"; e.setTodoCorrecto(false); RESULT=e; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("c3",2, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // c3 ::= 
            {
              NavesCamino RESULT =null;
		 NavesCamino naves = new NavesCamino(); naves.setTodoCorrecto(true); RESULT=naves; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("c3",2, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // c3 ::= COMA p1 
            {
              NavesCamino RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		NavesCamino a = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 RESULT=a; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("c3",2, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // c3 ::= c12 c3 
            {
              NavesCamino RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).right;
		NavesCamino a = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		NavesCamino e = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 if(e!=null){ if(e.getVerificador()==null){ e.setVerificador(a.getVerificador()); } else { parser.totalErrores += "Sub-atributo verificador en campo FLOTA sentenciado mas de una vez. Linea: "+aleft+" Columna: "+aright+".\n"; e.setTodoCorrecto(false); } } RESULT=e; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("c3",2, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // c3 ::= c11 c3 
            {
              NavesCamino RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).right;
		NavesCamino a = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		NavesCamino e = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 if(e!=null){ if(e.getTurnoLlegada()==null){ e.setTurnoLlegada(a.getTurnoLlegada()); } else { parser.totalErrores += "Sub-atributo turnoLlegada en campo FLOTA sentenciado mas de una vez. Linea: "+aleft+" Columna: "+aright+".\n"; e.setTodoCorrecto(false); } } RESULT=e; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("c3",2, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // c3 ::= c10 c3 
            {
              NavesCamino RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).right;
		NavesCamino a = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		NavesCamino e = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 if(e!=null){ if(e.getPorcentajeMuertes()==null){ e.setPorcentajeMuertes(a.getPorcentajeMuertes()); } else { parser.totalErrores += "Sub-atributo porcentajeMuertes en campo FLOTA sentenciado mas de una vez. Linea: "+aleft+" Columna: "+aright+".\n"; e.setTodoCorrecto(false); } } RESULT=e; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("c3",2, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // c3 ::= c9 c3 
            {
              NavesCamino RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).right;
		NavesCamino a = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		NavesCamino e = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 if(e!=null){ if(e.getNoJugadorAtaque()==null){ e.setNoJugadorAtaque(a.getNoJugadorAtaque()); } else { parser.totalErrores += "Sub-atributo noJugadorAtaque en campo FLOTA sentenciado mas de una vez. Linea: "+aleft+" Columna: "+aright+".\n"; e.setTodoCorrecto(false); } } RESULT=e; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("c3",2, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // c3 ::= c8 c3 
            {
              NavesCamino RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).right;
		NavesCamino a = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		NavesCamino e = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 if(e!=null){ if(e.getNoJugadorEnvio()==null){ e.setNoJugadorEnvio(a.getNoJugadorEnvio()); } else { parser.totalErrores += "Sub-atributo noJugadorEnvio en campo FLOTA sentenciado mas de una vez. Linea: "+aleft+" Columna: "+aright+".\n"; e.setTodoCorrecto(false); } } RESULT=e; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("c3",2, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // c3 ::= c7 c3 
            {
              NavesCamino RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).right;
		NavesCamino a = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		NavesCamino e = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 if(e!=null){ if(e.getNoNaves()==null){ e.setNoNaves(a.getNoNaves()); } else { parser.totalErrores += "Sub-atributo noNaves en campo FLOTA sentenciado mas de una vez. Linea: "+aleft+" Columna: "+aright+".\n"; e.setTodoCorrecto(false); } } RESULT=e; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("c3",2, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // c3 ::= c6 c3 
            {
              NavesCamino RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).right;
		NavesCamino a = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		NavesCamino e = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 if(e!=null){ if(e.getPlanetaDestino()==null){ e.setPlanetaDestino(a.getPlanetaDestino()); } else { parser.totalErrores += "Sub-atributo planetaDestino en campo FLOTA sentenciado mas de una vez. Linea: "+aleft+" Columna: "+aright+".\n"; e.setTodoCorrecto(false); } } RESULT=e; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("c3",2, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // c3 ::= c5 c3 
            {
              NavesCamino RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).right;
		NavesCamino a = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		NavesCamino e = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 if(e!=null){ if(e.getPlanetaOrigen()==null){ e.setPlanetaOrigen(a.getPlanetaOrigen()); } else { parser.totalErrores += "Sub-atributo planetaOrigen en campo FLOTA sentenciado mas de una vez. Linea: "+aleft+" Columna: "+aright+".\n"; e.setTodoCorrecto(false); } } RESULT=e; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("c3",2, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // c3 ::= c4 c3 
            {
              NavesCamino RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).right;
		NavesCamino a = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		NavesCamino e = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 if(e!=null){ if(e.getNoFlota()==null){ e.setNoFlota(a.getNoFlota()); } else { parser.totalErrores += "Sub-atributo noFlota en campo FLOTA sentenciado mas de una vez. Linea: "+aleft+" Columna: "+aright+".\n"; e.setTodoCorrecto(false); } } RESULT=e; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("c3",2, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // c2 ::= Flota AGRUPACION_A c3 AGRUPACION_B 
            {
              ArrayList<NavesCamino> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).right;
		NavesCamino a = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).value;
		 if(a.getNoFlota()==null) { parser.totalErrores += "Falta de atributo noFlota en campo FLOTA. Linea: "+aleft+" Columna: "+aright+".\n"; a.setTodoCorrecto(false); }
                                              if(a.getPlanetaOrigen()==null) { parser.totalErrores += "Falta de atributo noFlota en campo FLOTA. Linea: "+aleft+" Columna: "+aright+".\n"; a.setTodoCorrecto(false); }
                                              if(a.getPlanetaDestino()==null) { parser.totalErrores += "Falta de atributo noFlota en campo FLOTA. Linea: "+aleft+" Columna: "+aright+".\n"; a.setTodoCorrecto(false); }
                                              if(a.getNoNaves()==null) { parser.totalErrores += "Falta de atributo noFlota en campo FLOTA. Linea: "+aleft+" Columna: "+aright+".\n"; a.setTodoCorrecto(false); }
                                              if(a.getNoJugadorEnvio()==null) { parser.totalErrores += "Falta de atributo noFlota en campo FLOTA. Linea: "+aleft+" Columna: "+aright+".\n"; a.setTodoCorrecto(false); }
                                              if(a.getNoJugadorAtaque()==null) { parser.totalErrores += "Falta de atributo noFlota en campo FLOTA. Linea: "+aleft+" Columna: "+aright+".\n"; a.setTodoCorrecto(false); }
                                              if(a.getPorcentajeMuertes()==null) { parser.totalErrores += "Falta de atributo noFlota en campo FLOTA. Linea: "+aleft+" Columna: "+aright+".\n"; a.setTodoCorrecto(false); }
                                              if(a.getTurnoLlegada()==null) { parser.totalErrores += "Falta de atributo noFlota en campo FLOTA. Linea: "+aleft+" Columna: "+aright+".\n"; a.setTodoCorrecto(false); }
                                              if(a.getVerificador()==null) { parser.totalErrores += "Falta de atributo noFlota en campo FLOTA. Linea: "+aleft+" Columna: "+aright+".\n"; a.setTodoCorrecto(false); }
                                              if(a.getTodoCorrecto() == false) { RESULT=null; } else     { ArrayList<NavesCamino> listNaves = new ArrayList<>(); listNaves.add(a); RESULT=listNaves; } 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("c2",13, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-3)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // c2 ::= Flota AGRUPACION_A c3 AGRUPACION_B c2 
            {
              ArrayList<NavesCamino> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-2)).right;
		NavesCamino a = (NavesCamino)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		ArrayList<NavesCamino> e = (ArrayList<NavesCamino>)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 if(a.getNoFlota()==null){ parser.totalErrores += "Falta de atributo noFlota en campo FLOTA. Linea: "+aleft+" Columna: "+aright+".\n"; a.setTodoCorrecto(false); }
                                                        if(a.getPlanetaOrigen()==null){ parser.totalErrores += "Falta de atributo planetaOrigen en campo FLOTA. Linea: "+aleft+" Columna: "+aright+".\n"; a.setTodoCorrecto(false); }
                                                        if(a.getPlanetaDestino()==null){ parser.totalErrores += "Falta de atributo planetaDestino en campo FLOTA. Linea: "+aleft+" Columna: "+aright+".\n"; a.setTodoCorrecto(false); }
                                                        if(a.getNoNaves()==null){ parser.totalErrores += "Falta de atributo noNaves en campo FLOTA. Linea: "+aleft+" Columna: "+aright+".\n"; a.setTodoCorrecto(false); }
                                                        if(a.getNoJugadorEnvio()==null){ parser.totalErrores += "Falta de atributo noJugadorEnvio en campo FLOTA. Linea: "+aleft+" Columna: "+aright+".\n"; a.setTodoCorrecto(false); }
                                                        if(a.getNoJugadorAtaque()==null){ parser.totalErrores += "Falta de atributo noJugadorAtaque en campo FLOTA. Linea: "+aleft+" Columna: "+aright+".\n"; a.setTodoCorrecto(false); }
                                                        if(a.getPorcentajeMuertes()==null){ parser.totalErrores += "Falta de atributo porcentajeMuertes en campo FLOTA. Linea: "+aleft+" Columna: "+aright+".\n"; a.setTodoCorrecto(false); }
                                                        if(a.getTurnoLlegada()==null){ parser.totalErrores += "Falta de atributo turnoLlegada en campo FLOTA. Linea: "+aleft+" Columna: "+aright+".\n"; a.setTodoCorrecto(false); }
                                                        if(a.getVerificador()==null){ parser.totalErrores += "Falta de atributo verificador en campo FLOTA. Linea: "+aleft+" Columna: "+aright+".\n"; a.setTodoCorrecto(false); }
                                                        if(e == null){ RESULT=null; } else {      if(a.getTodoCorrecto() == false){ RESULT=null; } else { e.add(a); RESULT=e; } } 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("c2",13, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-4)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // c1 ::= ID DOS_PUNTOS AGRUPACION_A c2 AGRUPACION_B 
            {
              ArrayList<DatosAcciones> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-4)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-4)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-4)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).right;
		ArrayList<NavesCamino> b = (ArrayList<NavesCamino>)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).value;
		 if(b == null){ RESULT=null; } else { DatosAcciones datos = new DatosAcciones(); datos.setNombreJugador(a.toString()); datos.setListNaves(b); ArrayList<DatosAcciones> listAcciones = new ArrayList<>(); listAcciones.add(datos); RESULT=listAcciones; } 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("c1",14, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-4)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // c1 ::= ID DOS_PUNTOS AGRUPACION_A c2 AGRUPACION_B c1 
            {
              ArrayList<DatosAcciones> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-5)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-5)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-5)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-2)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-2)).right;
		ArrayList<NavesCamino> b = (ArrayList<NavesCamino>)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-2)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		ArrayList<DatosAcciones> c = (ArrayList<DatosAcciones>)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 if(c == null){ RESULT=null; } else { if(b == null) { RESULT=null; } else { DatosAcciones datos = new DatosAcciones(); datos.setNombreJugador(a.toString()); datos.setListNaves(b);  c.add(datos); RESULT=c; } } 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("c1",14, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-5)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // c ::= ACCIONES LLAVE_A LLAVE_B 
            {
              ArrayList<DatosAcciones> RESULT =null;
		 RESULT=new ArrayList<>(); 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("c",15, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-2)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // c ::= ACCIONES LLAVE_A c1 LLAVE_B 
            {
              ArrayList<DatosAcciones> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).right;
		ArrayList<DatosAcciones> a = (ArrayList<DatosAcciones>)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).value;
		 RESULT=a; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("c",15, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-3)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // p4 ::= error b 
            {
              AccionesOnline RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		AccionesOnline e = (AccionesOnline)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 parser.totalErrores += "Atributo en un campo SECUENCIAS sentenciado mas de unav vez.\n"; e.setTodoCorrecto(false);  RESULT=e; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("p4",37, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // p4 ::= e b 
            {
              AccionesOnline RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).right;
		ArrayList<ResumenTurno> a = (ArrayList<ResumenTurno>)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		AccionesOnline e = (AccionesOnline)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 if(e!=null){ if(e.getListResumen()==null){ if(a == null){ e.setTodoCorrecto(false); } else { e.setListResumen(a); } } else { parser.totalErrores += "Sub-atributo RESUMEN en campo SECUENCIAS sentenciado mas de una vez. Linea: "+aleft+" Columna: "+aright+".\n"; e.setTodoCorrecto(false); } } RESULT=e; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("p4",37, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // p4 ::= c b 
            {
              AccionesOnline RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).right;
		ArrayList<DatosAcciones> a = (ArrayList<DatosAcciones>)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		AccionesOnline e = (AccionesOnline)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 if(e!=null){ if(e.getDatosAcciones()==null){ if(a == null){ e.setTodoCorrecto(false); } else { e.setDatosAcciones(a); } } else { parser.totalErrores += "Sub-atributo ACCIONES en un campo SECUENCIAS sentenciado mas de una vez. Linea: "+aleft+" Columna: "+aright+".\n"; e.setTodoCorrecto(false); } } RESULT=e; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("p4",37, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // b ::= error b 
            {
              AccionesOnline RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		AccionesOnline e = (AccionesOnline)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 parser.totalErrores += "Atributo en un campo SECUENCIAS sentenciado mas de una vez.\n"; e.setTodoCorrecto(false); RESULT=e; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("b",36, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // b ::= 
            {
              AccionesOnline RESULT =null;
		 AccionesOnline online = new AccionesOnline(); online.setTodoCorrecto(false); RESULT=online; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("b",36, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // b ::= COMA p4 
            {
              AccionesOnline RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		AccionesOnline a = (AccionesOnline)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 RESULT=a; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("b",36, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // b ::= e b 
            {
              AccionesOnline RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).right;
		ArrayList<ResumenTurno> a = (ArrayList<ResumenTurno>)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		AccionesOnline e = (AccionesOnline)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 if(e!=null){ if(e.getListResumen()==null){ if(a == null){ e.setTodoCorrecto(false); } else { e.setListResumen(a); } } else { parser.totalErrores += "Sub-atributo RESUMEN en campo SECUENCIAS sentenciado mas de una vez. Linea: "+aleft+" Columna: "+aright+".\n"; e.setTodoCorrecto(false); } } RESULT=e; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("b",36, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // b ::= c b 
            {
              AccionesOnline RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).right;
		ArrayList<DatosAcciones> a = (ArrayList<DatosAcciones>)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()).right;
		AccionesOnline e = (AccionesOnline)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.peek()).value;
		 if(e!=null){ if(e.getDatosAcciones()==null){  if(a == null){ e.setTodoCorrecto(false); } else { e.setDatosAcciones(a); } } else { parser.totalErrores += "Sub-atributo ACCIONES en un campo SECUENCIAS sentenciado mas de una vez. Linea: "+aleft+" Columna: "+aright+".\n"; e.setTodoCorrecto(false); } } RESULT=e; 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("b",36, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // a ::= SECUENCIAS LLAVE_A b LLAVE_B 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).right;
		AccionesOnline a = (AccionesOnline)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).value;
		 if(a.getDatosAcciones()==null || a.getListResumen()==null){} else {  parser.listOnline.add(a);  } 
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("a",1, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-3)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= a 
            {
              Object RESULT =null;

              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          return CUP$SintaxOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)).value;
		RESULT = start_val;
              CUP$SintaxOnline$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.elementAt(CUP$SintaxOnline$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxOnline$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$SintaxOnline$parser.done_parsing();
          return CUP$SintaxOnline$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

