
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 27 01:50:38 CST 2020
//----------------------------------------------------

package gramaticas4;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AGRUPACION_A = 6;
  public static final int turno = 70;
  public static final int turnoJugador = 68;
  public static final int estadoJugador = 60;
  public static final int acumular = 18;
  public static final int noJugadorAtaque = 52;
  public static final int TURNO = 45;
  public static final int mostrarNaves = 20;
  public static final int ENTERO = 35;
  public static final int planetas = 30;
  public static final int produccion = 22;
  public static final int FACIL = 34;
  public static final int PLANETAS = 24;
  public static final int size = 14;
  public static final int noNaves = 50;
  public static final int DOS_PUNTOS = 8;
  public static final int alAzar = 15;
  public static final int finalizacion = 23;
  public static final int JUGANDO = 64;
  public static final int estado = 58;
  public static final int LLAVE_B = 5;
  public static final int NEUTRALES = 19;
  public static final int LLAVE_A = 4;
  public static final int GENERAL = 69;
  public static final int DIFICIL = 33;
  public static final int mostrarEstadisticas = 21;
  public static final int MAPA = 12;
  public static final int FUERA = 65;
  public static final int SECUENCIAS = 44;
  public static final int CONQUISTADO = 53;
  public static final int porcMuertes = 27;
  public static final int jugadorAtacante = 66;
  public static final int verificador = 55;
  public static final int Flota = 47;
  public static final int ID = 37;
  public static final int DECIMAL = 36;
  public static final int EOF = 0;
  public static final int turnoLlegada = 54;
  public static final int pNeutrales = 16;
  public static final int COMILLAS = 11;
  public static final int nombre = 25;
  public static final int IMPACTOS = 56;
  public static final int error = 1;
  public static final int color = 40;
  public static final int COMA = 9;
  public static final int planetaAtacante = 67;
  public static final int PLANETAS_NEUTRALES = 28;
  public static final int mensaje = 59;
  public static final int COLOR = 43;
  public static final int posY = 42;
  public static final int mapaCiego = 17;
  public static final int posX = 41;
  public static final int HUMANO = 32;
  public static final int id = 13;
  public static final int RESUMEN = 63;
  public static final int PUNTO = 10;
  public static final int tipo = 31;
  public static final int navesRestantes = 57;
  public static final int FALSO = 3;
  public static final int noJugadorEnvio = 51;
  public static final int filas = 38;
  public static final int JUGADORES = 29;
  public static final int ACCIONES = 46;
  public static final int planetaOrigen = 48;
  public static final int columnas = 39;
  public static final int naves = 26;
  public static final int VERDADERO = 2;
  public static final int planetaDestino = 49;
  public static final int VIVO = 62;
  public static final int noFlota = 61;
  public static final int AGRUPACION_B = 7;
}

