/* The following code was generated by JFlex 1.6.1 */

package gramaticas3;
import java_cup.runtime.Symbol;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>LexerReplay.flex</tt>
 */
public class AnalizadorLexico3 implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\10\1\10\1\72\1\10\1\10\22\0\1\10\1\0\1\26"+
    "\1\0\1\1\3\0\1\70\1\71\2\0\1\6\1\5\1\7\1\0"+
    "\1\2\11\3\1\25\6\0\1\30\1\1\1\43\1\63\1\45\1\65"+
    "\1\62\1\67\1\64\1\61\1\1\1\51\1\27\1\42\1\4\1\31"+
    "\1\1\1\50\1\52\1\47\1\46\2\1\1\55\1\56\1\1\1\23"+
    "\1\0\1\24\1\0\1\60\1\0\1\16\1\54\1\35\1\33\1\14"+
    "\1\15\1\44\1\1\1\32\1\57\1\1\1\17\1\37\1\40\1\36"+
    "\1\41\1\66\1\12\1\20\1\11\1\13\1\53\3\1\1\34\1\21"+
    "\1\0\1\22\7\0\1\72\u1fa2\0\1\72\1\72\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\3\2\4\1\5\1\6\1\1\5\3"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\21\3\1\2"+
    "\1\4\3\0\1\15\14\3\1\16\23\3\1\0\1\17"+
    "\44\3\1\0\1\20\1\3\1\21\6\3\1\22\1\23"+
    "\32\3\1\4\2\3\1\24\1\25\6\3\1\26\3\3"+
    "\1\27\11\3\1\30\5\3\1\31\1\32\2\3\1\33"+
    "\1\3\1\34\10\3\1\35\15\3\1\36\7\3\1\37"+
    "\3\3\1\40\1\3\1\41\10\3\1\42\4\3\1\43"+
    "\1\44\1\45\1\46\7\3\1\47\7\3\1\50\4\3"+
    "\1\51\11\3\1\52\1\53\1\54\2\3\1\55\11\3"+
    "\1\56\4\3\1\57\16\3\1\60\1\61\1\3\1\62"+
    "\1\3\1\63\10\3\1\64\5\3\1\65\5\3\1\66"+
    "\1\3\1\67\1\3\1\70\3\3\1\71\10\3\1\72"+
    "\1\73\1\74\1\3\1\75";

  private static int [] zzUnpackAction() {
    int [] result = new int[355];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\73\0\166\0\261\0\354\0\u0127\0\u0162\0\u019d"+
    "\0\u01d8\0\u0213\0\u024e\0\u0289\0\u02c4\0\73\0\73\0\73"+
    "\0\73\0\73\0\73\0\u02ff\0\u033a\0\u0375\0\u03b0\0\u03eb"+
    "\0\u0426\0\u0461\0\u049c\0\u04d7\0\u0512\0\u054d\0\u0588\0\u05c3"+
    "\0\u05fe\0\u0639\0\u0674\0\u06af\0\u06ea\0\u0725\0\u0127\0\u0162"+
    "\0\u0760\0\u0162\0\u079b\0\u07d6\0\u0811\0\u084c\0\u0887\0\u08c2"+
    "\0\u08fd\0\u0938\0\u0973\0\u09ae\0\u09e9\0\u0a24\0\166\0\u0a5f"+
    "\0\u0a9a\0\u0ad5\0\u0b10\0\u0b4b\0\u0b86\0\u0bc1\0\u0bfc\0\u0c37"+
    "\0\u0c72\0\u0cad\0\u0ce8\0\u0d23\0\u0d5e\0\u0d99\0\u0dd4\0\u0e0f"+
    "\0\u0e4a\0\u0e85\0\u0ec0\0\u0efb\0\u0f36\0\u0f71\0\u0fac\0\u0fe7"+
    "\0\u1022\0\u105d\0\u1098\0\u10d3\0\u110e\0\u1149\0\u1184\0\u11bf"+
    "\0\u11fa\0\u1235\0\u1270\0\u12ab\0\u12e6\0\u1321\0\u135c\0\u1397"+
    "\0\u13d2\0\u140d\0\u1448\0\u1483\0\u14be\0\u14f9\0\u1534\0\u156f"+
    "\0\u15aa\0\u15e5\0\u1620\0\u165b\0\u1696\0\u16d1\0\u170c\0\u1747"+
    "\0\u1782\0\166\0\u17bd\0\166\0\u17f8\0\u1833\0\u186e\0\u18a9"+
    "\0\u18e4\0\u191f\0\166\0\166\0\u195a\0\u1995\0\u19d0\0\u1a0b"+
    "\0\u1a46\0\u1a81\0\u1abc\0\u1af7\0\u1b32\0\u1b6d\0\u1ba8\0\u1be3"+
    "\0\u1c1e\0\u1c59\0\u1c94\0\u1ccf\0\u1d0a\0\u1d45\0\u1d80\0\u1dbb"+
    "\0\u1df6\0\u1e31\0\u1e6c\0\u1ea7\0\u1ee2\0\u1f1d\0\73\0\u1f58"+
    "\0\u1f93\0\166\0\166\0\u1fce\0\u2009\0\u2044\0\u207f\0\u20ba"+
    "\0\u20f5\0\166\0\u2130\0\u216b\0\u21a6\0\u21e1\0\u221c\0\u2257"+
    "\0\u2292\0\u22cd\0\u2308\0\u2343\0\u237e\0\u23b9\0\u23f4\0\166"+
    "\0\u242f\0\u246a\0\u24a5\0\u24e0\0\u251b\0\166\0\166\0\u2556"+
    "\0\u2591\0\u25cc\0\u2607\0\166\0\u2642\0\u267d\0\u26b8\0\u26f3"+
    "\0\u272e\0\u2769\0\u27a4\0\u27df\0\166\0\u281a\0\u2855\0\u2890"+
    "\0\u28cb\0\u2906\0\u2941\0\u297c\0\u29b7\0\u29f2\0\u2a2d\0\u2a68"+
    "\0\u2aa3\0\u2ade\0\166\0\u2b19\0\u2b54\0\u2b8f\0\u2bca\0\u2c05"+
    "\0\u2c40\0\u2c7b\0\166\0\u2cb6\0\u2cf1\0\u2d2c\0\166\0\u2d67"+
    "\0\166\0\u2da2\0\u2ddd\0\u2e18\0\u2e53\0\u2e8e\0\u2ec9\0\u2f04"+
    "\0\u2f3f\0\166\0\u2f7a\0\u2fb5\0\u2ff0\0\u302b\0\166\0\166"+
    "\0\u3066\0\166\0\u30a1\0\u30dc\0\u3117\0\u3152\0\u318d\0\u31c8"+
    "\0\u3203\0\u323e\0\u3279\0\u32b4\0\u32ef\0\u332a\0\u3365\0\u33a0"+
    "\0\u33db\0\166\0\u3416\0\u3451\0\u348c\0\u34c7\0\166\0\u3502"+
    "\0\u353d\0\u3578\0\u35b3\0\u35ee\0\u3629\0\u3664\0\u369f\0\u36da"+
    "\0\166\0\166\0\166\0\u3715\0\u3750\0\166\0\u378b\0\u37c6"+
    "\0\u3801\0\u383c\0\u3877\0\u38b2\0\u38ed\0\u3928\0\u3963\0\166"+
    "\0\u399e\0\u39d9\0\u3a14\0\u3a4f\0\166\0\u3a8a\0\u3ac5\0\u3b00"+
    "\0\u3b3b\0\u3b76\0\u3bb1\0\u3bec\0\u3c27\0\u3c62\0\u3c9d\0\u3cd8"+
    "\0\u3d13\0\u3d4e\0\u3d89\0\166\0\166\0\u3dc4\0\166\0\u3dff"+
    "\0\166\0\u3e3a\0\u3e75\0\u3eb0\0\u3eeb\0\u3f26\0\u3f61\0\u3f9c"+
    "\0\u3fd7\0\166\0\u4012\0\u404d\0\u4088\0\u40c3\0\u40fe\0\166"+
    "\0\u4139\0\u4174\0\u41af\0\u41ea\0\u4225\0\166\0\u4260\0\166"+
    "\0\u429b\0\166\0\u42d6\0\u4311\0\u434c\0\166\0\u4387\0\u43c2"+
    "\0\u43fd\0\u4438\0\u4473\0\u44ae\0\u44e9\0\u4524\0\166\0\166"+
    "\0\166\0\u455f\0\166";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[355];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\3\1\2\1\6\1\7"+
    "\1\10\1\11\2\3\1\12\1\13\1\14\1\3\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\2\3\1\30\1\3\1\31\1\32\1\33"+
    "\1\34\4\3\1\35\2\3\1\36\1\37\5\3\1\40"+
    "\1\3\1\41\1\42\1\43\1\3\1\44\1\45\1\2"+
    "\75\0\5\3\3\0\10\3\6\0\41\3\5\0\2\46"+
    "\2\0\1\47\1\50\65\0\2\5\2\0\1\47\1\50"+
    "\65\0\2\47\2\0\1\51\66\0\2\52\77\0\1\10"+
    "\63\0\5\3\3\0\1\3\1\53\1\54\5\3\6\0"+
    "\3\3\1\55\35\3\4\0\5\3\3\0\7\3\1\56"+
    "\6\0\41\3\4\0\5\3\3\0\5\3\1\57\2\3"+
    "\6\0\3\3\1\60\35\3\4\0\5\3\3\0\6\3"+
    "\1\61\1\3\6\0\6\3\1\62\32\3\4\0\5\3"+
    "\3\0\10\3\6\0\3\3\1\63\35\3\4\0\5\3"+
    "\3\0\10\3\6\0\1\3\1\64\37\3\4\0\5\3"+
    "\3\0\10\3\6\0\14\3\1\65\24\3\4\0\5\3"+
    "\3\0\10\3\6\0\22\3\1\66\16\3\4\0\5\3"+
    "\3\0\10\3\6\0\4\3\1\67\34\3\4\0\5\3"+
    "\3\0\10\3\6\0\7\3\1\70\31\3\4\0\5\3"+
    "\3\0\3\3\1\71\1\3\1\72\2\3\6\0\7\3"+
    "\1\73\31\3\4\0\5\3\3\0\5\3\1\74\2\3"+
    "\6\0\7\3\1\75\31\3\4\0\5\3\3\0\1\3"+
    "\1\76\4\3\1\77\1\3\6\0\7\3\1\100\31\3"+
    "\4\0\5\3\3\0\10\3\6\0\16\3\1\101\22\3"+
    "\4\0\5\3\3\0\10\3\6\0\17\3\1\102\21\3"+
    "\4\0\5\3\3\0\10\3\6\0\16\3\1\103\22\3"+
    "\4\0\5\3\3\0\3\3\1\104\4\3\6\0\41\3"+
    "\4\0\5\3\3\0\10\3\6\0\17\3\1\105\21\3"+
    "\4\0\5\3\3\0\10\3\6\0\35\3\1\106\3\3"+
    "\4\0\5\3\3\0\10\3\6\0\1\107\40\3\4\0"+
    "\5\3\3\0\6\3\1\110\1\3\6\0\1\3\1\111"+
    "\37\3\4\0\5\3\3\0\10\3\6\0\17\3\1\112"+
    "\21\3\10\0\1\113\67\0\2\46\2\0\1\47\66\0"+
    "\2\51\2\0\1\114\65\0\5\3\3\0\2\3\1\115"+
    "\5\3\6\0\41\3\4\0\5\3\3\0\1\3\1\116"+
    "\6\3\6\0\41\3\4\0\5\3\3\0\10\3\6\0"+
    "\12\3\1\117\26\3\4\0\5\3\3\0\1\120\7\3"+
    "\6\0\41\3\4\0\5\3\3\0\6\3\1\121\1\3"+
    "\6\0\41\3\4\0\5\3\3\0\6\3\1\122\1\3"+
    "\6\0\11\3\1\123\27\3\4\0\5\3\3\0\10\3"+
    "\6\0\1\3\1\124\37\3\4\0\5\3\3\0\2\3"+
    "\1\125\5\3\6\0\41\3\4\0\5\3\3\0\10\3"+
    "\6\0\5\3\1\126\33\3\4\0\5\3\3\0\10\3"+
    "\6\0\2\3\1\127\36\3\4\0\5\3\3\0\10\3"+
    "\6\0\14\3\1\130\24\3\4\0\5\3\3\0\10\3"+
    "\6\0\1\3\1\131\37\3\4\0\5\3\3\0\6\3"+
    "\1\132\1\3\6\0\41\3\4\0\5\3\3\0\10\3"+
    "\6\0\11\3\1\133\27\3\4\0\5\3\3\0\10\3"+
    "\6\0\12\3\1\134\26\3\4\0\5\3\3\0\7\3"+
    "\1\135\6\0\41\3\4\0\5\3\3\0\10\3\6\0"+
    "\24\3\1\136\14\3\4\0\5\3\3\0\10\3\6\0"+
    "\10\3\1\137\2\3\1\140\16\3\1\141\3\3\1\142"+
    "\2\3\4\0\5\3\3\0\10\3\6\0\7\3\1\143"+
    "\31\3\4\0\5\3\3\0\5\3\1\144\2\3\6\0"+
    "\41\3\4\0\5\3\3\0\1\3\1\145\5\3\1\146"+
    "\6\0\41\3\4\0\5\3\3\0\10\3\6\0\17\3"+
    "\1\147\21\3\4\0\5\3\3\0\10\3\6\0\21\3"+
    "\1\150\17\3\4\0\5\3\3\0\10\3\6\0\14\3"+
    "\1\151\24\3\4\0\5\3\3\0\1\3\1\152\6\3"+
    "\6\0\41\3\4\0\5\3\3\0\10\3\6\0\33\3"+
    "\1\153\5\3\4\0\5\3\3\0\10\3\6\0\36\3"+
    "\1\154\2\3\4\0\5\3\3\0\10\3\6\0\2\3"+
    "\1\155\36\3\4\0\5\3\3\0\10\3\6\0\7\3"+
    "\1\156\31\3\4\0\5\3\3\0\10\3\6\0\14\3"+
    "\1\157\24\3\4\0\5\3\3\0\10\3\6\0\1\160"+
    "\40\3\5\0\2\161\71\0\2\114\70\0\5\3\3\0"+
    "\3\3\1\162\4\3\6\0\41\3\4\0\5\3\3\0"+
    "\10\3\6\0\11\3\1\163\27\3\4\0\5\3\3\0"+
    "\10\3\6\0\7\3\1\164\31\3\4\0\5\3\3\0"+
    "\5\3\1\165\2\3\6\0\41\3\4\0\5\3\3\0"+
    "\7\3\1\166\6\0\41\3\4\0\5\3\3\0\5\3"+
    "\1\167\2\3\6\0\41\3\4\0\5\3\3\0\5\3"+
    "\1\170\2\3\6\0\41\3\4\0\5\3\3\0\10\3"+
    "\6\0\5\3\1\171\33\3\4\0\5\3\3\0\10\3"+
    "\6\0\10\3\1\172\30\3\4\0\5\3\3\0\3\3"+
    "\1\173\4\3\6\0\41\3\4\0\5\3\3\0\10\3"+
    "\6\0\1\3\1\174\37\3\4\0\5\3\3\0\10\3"+
    "\6\0\35\3\1\175\3\3\4\0\5\3\3\0\10\3"+
    "\6\0\13\3\1\176\25\3\4\0\5\3\3\0\2\3"+
    "\1\177\5\3\6\0\7\3\1\200\31\3\4\0\5\3"+
    "\3\0\7\3\1\201\6\0\41\3\4\0\5\3\3\0"+
    "\5\3\1\202\2\3\6\0\41\3\4\0\5\3\3\0"+
    "\1\203\7\3\6\0\41\3\4\0\5\3\3\0\3\3"+
    "\1\204\4\3\6\0\41\3\4\0\5\3\3\0\10\3"+
    "\6\0\25\3\1\205\13\3\4\0\5\3\3\0\5\3"+
    "\1\206\2\3\6\0\41\3\4\0\5\3\3\0\2\3"+
    "\1\207\5\3\6\0\41\3\4\0\5\3\3\0\6\3"+
    "\1\210\1\3\6\0\41\3\4\0\5\3\3\0\10\3"+
    "\6\0\4\3\1\211\34\3\4\0\5\3\3\0\10\3"+
    "\6\0\11\3\1\212\27\3\4\0\5\3\3\0\10\3"+
    "\6\0\6\3\1\213\32\3\4\0\5\3\3\0\10\3"+
    "\6\0\3\3\1\214\35\3\4\0\5\3\3\0\10\3"+
    "\6\0\20\3\1\215\20\3\4\0\5\3\3\0\10\3"+
    "\6\0\13\3\1\216\25\3\4\0\5\3\3\0\10\3"+
    "\6\0\17\3\1\217\21\3\4\0\5\3\3\0\10\3"+
    "\6\0\3\3\1\220\35\3\4\0\5\3\3\0\10\3"+
    "\6\0\1\3\1\221\37\3\4\0\5\3\3\0\10\3"+
    "\6\0\35\3\1\222\3\3\4\0\5\3\3\0\10\3"+
    "\6\0\1\3\1\223\37\3\4\0\5\3\3\0\1\224"+
    "\7\3\6\0\41\3\4\0\5\3\3\0\10\3\6\0"+
    "\35\3\1\225\3\3\4\0\5\3\3\0\10\3\6\0"+
    "\1\3\1\226\37\3\5\0\2\161\65\0\1\227\2\0"+
    "\5\3\3\0\10\3\6\0\7\3\1\230\31\3\4\0"+
    "\5\3\3\0\10\3\6\0\4\3\1\231\34\3\4\0"+
    "\5\3\3\0\3\3\1\232\4\3\6\0\41\3\4\0"+
    "\5\3\3\0\7\3\1\233\6\0\41\3\4\0\5\3"+
    "\3\0\6\3\1\234\1\3\6\0\41\3\4\0\5\3"+
    "\3\0\5\3\1\235\2\3\6\0\41\3\4\0\5\3"+
    "\3\0\2\3\1\236\5\3\6\0\41\3\4\0\3\3"+
    "\1\237\1\3\3\0\10\3\6\0\41\3\4\0\5\3"+
    "\3\0\10\3\6\0\16\3\1\240\22\3\4\0\5\3"+
    "\3\0\10\3\6\0\10\3\1\241\30\3\4\0\5\3"+
    "\3\0\1\3\1\242\6\3\6\0\41\3\4\0\5\3"+
    "\3\0\5\3\1\243\2\3\6\0\41\3\4\0\5\3"+
    "\3\0\10\3\6\0\14\3\1\244\24\3\4\0\5\3"+
    "\3\0\1\3\1\245\6\3\6\0\41\3\4\0\5\3"+
    "\3\0\7\3\1\246\6\0\41\3\4\0\5\3\3\0"+
    "\1\3\1\247\6\3\6\0\41\3\4\0\5\3\3\0"+
    "\10\3\6\0\24\3\1\250\14\3\4\0\5\3\3\0"+
    "\10\3\6\0\15\3\1\251\23\3\4\0\5\3\3\0"+
    "\10\3\6\0\7\3\1\252\31\3\4\0\5\3\3\0"+
    "\2\3\1\253\5\3\6\0\41\3\4\0\5\3\3\0"+
    "\3\3\1\254\4\3\6\0\41\3\4\0\5\3\3\0"+
    "\3\3\1\255\4\3\6\0\41\3\4\0\5\3\3\0"+
    "\10\3\6\0\6\3\1\256\32\3\4\0\5\3\3\0"+
    "\10\3\6\0\21\3\1\257\17\3\4\0\3\3\1\260"+
    "\1\3\3\0\10\3\6\0\41\3\4\0\5\3\3\0"+
    "\10\3\6\0\16\3\1\261\22\3\4\0\5\3\3\0"+
    "\4\3\1\262\3\3\6\0\41\3\4\0\5\3\3\0"+
    "\10\3\6\0\34\3\1\263\4\3\4\0\5\3\3\0"+
    "\10\3\6\0\14\3\1\264\24\3\4\0\5\3\3\0"+
    "\10\3\6\0\14\3\1\265\24\3\4\0\5\3\3\0"+
    "\5\3\1\266\2\3\6\0\41\3\4\0\5\3\3\0"+
    "\10\3\6\0\22\3\1\267\16\3\4\0\5\3\3\0"+
    "\10\3\6\0\13\3\1\270\25\3\4\0\5\3\3\0"+
    "\10\3\6\0\22\3\1\271\16\3\4\0\5\3\3\0"+
    "\10\3\6\0\7\3\1\272\31\3\4\0\5\3\3\0"+
    "\10\3\6\0\3\3\1\273\35\3\4\0\5\3\3\0"+
    "\1\3\1\274\6\3\6\0\41\3\4\0\5\3\3\0"+
    "\6\3\1\275\1\3\6\0\41\3\4\0\5\3\3\0"+
    "\10\3\6\0\13\3\1\276\25\3\4\0\5\3\3\0"+
    "\10\3\6\0\20\3\1\277\20\3\4\0\5\3\3\0"+
    "\10\3\6\0\11\3\1\300\27\3\4\0\5\3\3\0"+
    "\10\3\6\0\30\3\1\301\10\3\4\0\5\3\3\0"+
    "\10\3\6\0\3\3\1\302\35\3\4\0\5\3\3\0"+
    "\5\3\1\303\2\3\6\0\41\3\4\0\5\3\3\0"+
    "\10\3\6\0\21\3\1\304\17\3\4\0\5\3\3\0"+
    "\3\3\1\305\4\3\6\0\41\3\4\0\5\3\3\0"+
    "\3\3\1\306\4\3\6\0\41\3\4\0\5\3\3\0"+
    "\5\3\1\307\2\3\6\0\41\3\4\0\5\3\3\0"+
    "\1\310\7\3\6\0\41\3\4\0\5\3\3\0\10\3"+
    "\6\0\6\3\1\311\32\3\4\0\5\3\3\0\1\312"+
    "\7\3\6\0\41\3\4\0\5\3\3\0\10\3\6\0"+
    "\11\3\1\313\27\3\4\0\5\3\3\0\10\3\6\0"+
    "\3\3\1\314\35\3\4\0\5\3\3\0\10\3\6\0"+
    "\1\3\1\315\37\3\4\0\5\3\3\0\10\3\6\0"+
    "\13\3\1\316\25\3\4\0\5\3\3\0\10\3\6\0"+
    "\3\3\1\317\35\3\4\0\3\3\1\320\1\3\3\0"+
    "\10\3\6\0\41\3\4\0\5\3\3\0\10\3\6\0"+
    "\35\3\1\321\3\3\4\0\5\3\3\0\10\3\6\0"+
    "\20\3\1\322\20\3\4\0\3\3\1\323\1\3\3\0"+
    "\10\3\6\0\41\3\4\0\5\3\3\0\6\3\1\324"+
    "\1\3\6\0\41\3\4\0\5\3\3\0\10\3\6\0"+
    "\32\3\1\325\6\3\4\0\5\3\3\0\10\3\6\0"+
    "\5\3\1\326\33\3\4\0\5\3\3\0\5\3\1\327"+
    "\2\3\6\0\41\3\4\0\5\3\3\0\10\3\6\0"+
    "\16\3\1\330\22\3\4\0\5\3\3\0\10\3\6\0"+
    "\1\3\1\331\37\3\4\0\5\3\3\0\5\3\1\332"+
    "\2\3\6\0\41\3\4\0\5\3\3\0\3\3\1\333"+
    "\4\3\6\0\41\3\4\0\5\3\3\0\3\3\1\334"+
    "\4\3\6\0\41\3\4\0\5\3\3\0\1\3\1\335"+
    "\6\3\6\0\41\3\4\0\5\3\3\0\3\3\1\336"+
    "\4\3\6\0\41\3\4\0\5\3\3\0\7\3\1\337"+
    "\6\0\41\3\4\0\5\3\3\0\10\3\6\0\4\3"+
    "\1\340\34\3\4\0\5\3\3\0\5\3\1\341\2\3"+
    "\6\0\41\3\4\0\5\3\3\0\10\3\6\0\6\3"+
    "\1\342\32\3\4\0\5\3\3\0\5\3\1\343\2\3"+
    "\6\0\41\3\4\0\5\3\3\0\1\344\7\3\6\0"+
    "\41\3\4\0\5\3\3\0\10\3\6\0\7\3\1\345"+
    "\31\3\4\0\5\3\3\0\10\3\6\0\22\3\1\346"+
    "\16\3\4\0\5\3\3\0\10\3\6\0\14\3\1\347"+
    "\24\3\4\0\5\3\3\0\10\3\6\0\6\3\1\350"+
    "\32\3\4\0\5\3\3\0\10\3\6\0\21\3\1\351"+
    "\17\3\4\0\5\3\3\0\10\3\6\0\22\3\1\352"+
    "\16\3\4\0\3\3\1\353\1\3\3\0\10\3\6\0"+
    "\41\3\4\0\5\3\3\0\3\3\1\354\4\3\6\0"+
    "\41\3\4\0\5\3\3\0\2\3\1\355\5\3\6\0"+
    "\41\3\4\0\5\3\3\0\5\3\1\356\2\3\6\0"+
    "\41\3\4\0\5\3\3\0\1\3\1\357\6\3\6\0"+
    "\41\3\4\0\5\3\3\0\10\3\6\0\23\3\1\360"+
    "\15\3\4\0\5\3\3\0\10\3\6\0\23\3\1\361"+
    "\15\3\4\0\5\3\3\0\7\3\1\362\6\0\41\3"+
    "\4\0\5\3\3\0\10\3\6\0\15\3\1\363\23\3"+
    "\4\0\5\3\3\0\10\3\6\0\13\3\1\364\2\3"+
    "\1\365\22\3\4\0\5\3\3\0\7\3\1\366\6\0"+
    "\41\3\4\0\5\3\3\0\10\3\6\0\7\3\1\367"+
    "\31\3\4\0\5\3\3\0\10\3\6\0\3\3\1\370"+
    "\35\3\4\0\3\3\1\371\1\3\3\0\7\3\1\372"+
    "\6\0\34\3\1\373\4\3\4\0\5\3\3\0\5\3"+
    "\1\374\2\3\6\0\41\3\4\0\5\3\3\0\10\3"+
    "\6\0\11\3\1\375\27\3\4\0\5\3\3\0\10\3"+
    "\6\0\16\3\1\376\22\3\4\0\5\3\3\0\10\3"+
    "\6\0\35\3\1\377\3\3\4\0\5\3\3\0\5\3"+
    "\1\u0100\2\3\6\0\41\3\4\0\5\3\3\0\10\3"+
    "\6\0\16\3\1\u0101\22\3\4\0\5\3\3\0\10\3"+
    "\6\0\23\3\1\u0102\15\3\4\0\5\3\3\0\10\3"+
    "\6\0\15\3\1\u0103\23\3\4\0\5\3\3\0\10\3"+
    "\6\0\15\3\1\u0104\23\3\4\0\5\3\3\0\10\3"+
    "\6\0\6\3\1\u0105\32\3\4\0\5\3\3\0\10\3"+
    "\6\0\31\3\1\u0106\7\3\4\0\5\3\3\0\10\3"+
    "\6\0\7\3\1\u0107\31\3\4\0\5\3\3\0\5\3"+
    "\1\u0108\2\3\6\0\41\3\4\0\5\3\3\0\7\3"+
    "\1\u0109\6\0\41\3\4\0\5\3\3\0\1\u010a\7\3"+
    "\6\0\41\3\4\0\5\3\3\0\1\3\1\u010b\6\3"+
    "\6\0\41\3\4\0\5\3\3\0\10\3\6\0\7\3"+
    "\1\u010c\31\3\4\0\5\3\3\0\1\3\1\u010d\6\3"+
    "\6\0\41\3\4\0\5\3\3\0\10\3\6\0\13\3"+
    "\1\u010e\25\3\4\0\5\3\3\0\3\3\1\u010f\4\3"+
    "\6\0\41\3\4\0\5\3\3\0\10\3\6\0\30\3"+
    "\1\u0110\10\3\4\0\5\3\3\0\10\3\6\0\26\3"+
    "\1\u0111\1\u0112\11\3\4\0\5\3\3\0\10\3\6\0"+
    "\23\3\1\u0113\15\3\4\0\5\3\3\0\10\3\6\0"+
    "\1\3\1\u0114\37\3\4\0\5\3\3\0\10\3\6\0"+
    "\4\3\1\u0115\34\3\4\0\5\3\3\0\10\3\6\0"+
    "\23\3\1\u0116\15\3\4\0\5\3\3\0\5\3\1\u0117"+
    "\2\3\6\0\41\3\4\0\5\3\3\0\5\3\1\u0118"+
    "\2\3\6\0\41\3\4\0\5\3\3\0\10\3\6\0"+
    "\3\3\1\u0119\35\3\4\0\5\3\3\0\10\3\6\0"+
    "\13\3\1\u011a\25\3\4\0\5\3\3\0\10\3\6\0"+
    "\24\3\1\u011b\14\3\4\0\5\3\3\0\1\u011c\7\3"+
    "\6\0\41\3\4\0\5\3\3\0\5\3\1\u011d\2\3"+
    "\6\0\41\3\4\0\5\3\3\0\10\3\6\0\1\3"+
    "\1\u011e\14\3\1\u011f\22\3\4\0\5\3\3\0\10\3"+
    "\6\0\11\3\1\u0120\27\3\4\0\5\3\3\0\10\3"+
    "\6\0\3\3\1\u0121\35\3\4\0\5\3\3\0\3\3"+
    "\1\u0122\4\3\6\0\41\3\4\0\5\3\3\0\7\3"+
    "\1\u0123\6\0\41\3\4\0\5\3\3\0\3\3\1\u0124"+
    "\4\3\6\0\41\3\4\0\5\3\3\0\10\3\6\0"+
    "\23\3\1\u0125\15\3\4\0\5\3\3\0\10\3\6\0"+
    "\7\3\1\u0126\31\3\4\0\5\3\3\0\10\3\6\0"+
    "\4\3\1\u0127\34\3\4\0\5\3\3\0\10\3\6\0"+
    "\4\3\1\u0128\34\3\4\0\5\3\3\0\10\3\6\0"+
    "\7\3\1\u0129\31\3\4\0\5\3\3\0\10\3\6\0"+
    "\16\3\1\u012a\22\3\4\0\5\3\3\0\3\3\1\u012b"+
    "\4\3\6\0\41\3\4\0\5\3\3\0\5\3\1\u012c"+
    "\2\3\6\0\41\3\4\0\5\3\3\0\10\3\6\0"+
    "\11\3\1\u012d\27\3\4\0\5\3\3\0\1\u012e\7\3"+
    "\6\0\41\3\4\0\5\3\3\0\10\3\6\0\11\3"+
    "\1\u012f\27\3\4\0\5\3\3\0\10\3\6\0\15\3"+
    "\1\u0130\23\3\4\0\5\3\3\0\2\3\1\u0131\5\3"+
    "\6\0\41\3\4\0\5\3\3\0\1\u0132\7\3\6\0"+
    "\41\3\4\0\5\3\3\0\10\3\6\0\1\u0133\40\3"+
    "\4\0\5\3\3\0\1\3\1\u0134\6\3\6\0\41\3"+
    "\4\0\5\3\3\0\5\3\1\u0135\2\3\6\0\41\3"+
    "\4\0\5\3\3\0\10\3\6\0\7\3\1\u0136\31\3"+
    "\4\0\5\3\3\0\10\3\6\0\11\3\1\u0137\27\3"+
    "\4\0\5\3\3\0\10\3\6\0\17\3\1\u0138\21\3"+
    "\4\0\5\3\3\0\7\3\1\u0139\6\0\41\3\4\0"+
    "\5\3\3\0\10\3\6\0\4\3\1\u013a\34\3\4\0"+
    "\5\3\3\0\1\u013b\7\3\6\0\41\3\4\0\5\3"+
    "\3\0\5\3\1\u013c\2\3\6\0\41\3\4\0\5\3"+
    "\3\0\10\3\6\0\24\3\1\u013d\14\3\4\0\5\3"+
    "\3\0\3\3\1\u013e\4\3\6\0\41\3\4\0\5\3"+
    "\3\0\1\u013f\7\3\6\0\41\3\4\0\5\3\3\0"+
    "\10\3\6\0\3\3\1\u0140\35\3\4\0\5\3\3\0"+
    "\2\3\1\u0141\5\3\6\0\41\3\4\0\5\3\3\0"+
    "\1\3\1\u0142\6\3\6\0\41\3\4\0\5\3\3\0"+
    "\10\3\6\0\20\3\1\u0143\20\3\4\0\5\3\3\0"+
    "\10\3\6\0\3\3\1\u0144\35\3\4\0\5\3\3\0"+
    "\3\3\1\u0145\4\3\6\0\41\3\4\0\5\3\3\0"+
    "\10\3\6\0\37\3\1\u0146\1\3\4\0\5\3\3\0"+
    "\10\3\6\0\3\3\1\u0147\35\3\4\0\5\3\3\0"+
    "\10\3\6\0\11\3\1\u0148\27\3\4\0\5\3\3\0"+
    "\1\3\1\u0149\6\3\6\0\41\3\4\0\5\3\3\0"+
    "\10\3\6\0\11\3\1\u014a\27\3\4\0\5\3\3\0"+
    "\3\3\1\u014b\4\3\6\0\41\3\4\0\5\3\3\0"+
    "\10\3\6\0\21\3\1\u014c\17\3\4\0\5\3\3\0"+
    "\7\3\1\u014d\6\0\41\3\4\0\5\3\3\0\7\3"+
    "\1\u014e\6\0\41\3\4\0\5\3\3\0\2\3\1\u014f"+
    "\5\3\6\0\41\3\4\0\5\3\3\0\10\3\6\0"+
    "\7\3\1\u0150\31\3\4\0\5\3\3\0\5\3\1\u0151"+
    "\2\3\6\0\41\3\4\0\5\3\3\0\10\3\6\0"+
    "\7\3\1\u0152\31\3\4\0\5\3\3\0\1\3\1\u0153"+
    "\6\3\6\0\41\3\4\0\5\3\3\0\10\3\6\0"+
    "\1\3\1\u0154\37\3\4\0\5\3\3\0\1\u0155\7\3"+
    "\6\0\41\3\4\0\5\3\3\0\3\3\1\u0156\4\3"+
    "\6\0\41\3\4\0\5\3\3\0\6\3\1\u0157\1\3"+
    "\6\0\41\3\4\0\5\3\3\0\1\u0158\7\3\6\0"+
    "\41\3\4\0\5\3\3\0\10\3\6\0\22\3\1\u0159"+
    "\16\3\4\0\5\3\3\0\10\3\6\0\3\3\1\u015a"+
    "\35\3\4\0\5\3\3\0\3\3\1\u015b\4\3\6\0"+
    "\41\3\4\0\5\3\3\0\3\3\1\u015c\4\3\6\0"+
    "\41\3\4\0\5\3\3\0\10\3\6\0\16\3\1\u015d"+
    "\22\3\4\0\5\3\3\0\10\3\6\0\6\3\1\u015e"+
    "\32\3\4\0\5\3\3\0\7\3\1\u015f\6\0\41\3"+
    "\4\0\5\3\3\0\7\3\1\u0160\6\0\41\3\4\0"+
    "\5\3\3\0\10\3\6\0\23\3\1\u0161\15\3\4\0"+
    "\5\3\3\0\5\3\1\u0162\2\3\6\0\41\3\4\0"+
    "\5\3\3\0\7\3\1\u0163\6\0\41\3\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[17818];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\13\1\6\11\23\1\3\0\41\1\1\0"+
    "\45\1\1\0\45\1\1\11\314\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[355];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private Symbol symbol(int tipo){
        return new Symbol(tipo, yyline+1, yycolumn+1);
    }

    private Symbol symbol(int tipo, Object value){
        return new Symbol(tipo, yyline+1, yycolumn+1, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnalizadorLexico3(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 208) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { /*Ignore*/
            }
          case 62: break;
          case 2: 
            { 
            }
          case 63: break;
          case 3: 
            { return symbol(sym.ID, new String(yytext()));
            }
          case 64: break;
          case 4: 
            { return symbol(sym.ENTERO, new Integer(yytext()));
            }
          case 65: break;
          case 5: 
            { return symbol(sym.COMA);
            }
          case 66: break;
          case 6: 
            { return symbol(sym.PUNTO);
            }
          case 67: break;
          case 7: 
            { return symbol(sym.LLAVE_A);
            }
          case 68: break;
          case 8: 
            { return symbol(sym.LLAVE_B);
            }
          case 69: break;
          case 9: 
            { return symbol(sym.AGRUPACION_A);
            }
          case 70: break;
          case 10: 
            { return symbol(sym.AGRUPACION_B);
            }
          case 71: break;
          case 11: 
            { return symbol(sym.DOS_PUNTOS);
            }
          case 72: break;
          case 12: 
            { return symbol(sym.COMILLAS);
            }
          case 73: break;
          case 13: 
            { return symbol(sym.DECIMAL, new Double(yytext()));
            }
          case 74: break;
          case 14: 
            { return symbol(sym.id);
            }
          case 75: break;
          case 15: 
            { return symbol(sym.COLOR, new String(yytext()));
            }
          case 76: break;
          case 16: 
            { return symbol(sym.VERDADERO, new String(yytext()));
            }
          case 77: break;
          case 17: 
            { return symbol(sym.tipo);
            }
          case 78: break;
          case 18: 
            { return symbol(sym.size);
            }
          case 79: break;
          case 19: 
            { return symbol(sym.MAPA);
            }
          case 80: break;
          case 20: 
            { return symbol(sym.FALSO, new String(yytext()));
            }
          case 81: break;
          case 21: 
            { return symbol(sym.filas);
            }
          case 82: break;
          case 22: 
            { return symbol(sym.color);
            }
          case 83: break;
          case 23: 
            { return symbol(sym.naves);
            }
          case 84: break;
          case 24: 
            { return symbol(sym.TURNO);
            }
          case 85: break;
          case 25: 
            { return symbol(sym.Flota);
            }
          case 86: break;
          case 26: 
            { return symbol(sym.FACIL, new String(yytext()));
            }
          case 87: break;
          case 27: 
            { return symbol(sym.estado);
            }
          case 88: break;
          case 28: 
            { return symbol(sym.alAzar);
            }
          case 89: break;
          case 29: 
            { return symbol(sym.nombre);
            }
          case 90: break;
          case 30: 
            { return symbol(sym.HUMANO, new String(yytext()));
            }
          case 91: break;
          case 31: 
            { return symbol(sym.mensaje);
            }
          case 92: break;
          case 32: 
            { return symbol(sym.noNaves);
            }
          case 93: break;
          case 33: 
            { return symbol(sym.noFlota);
            }
          case 94: break;
          case 34: 
            { return symbol(sym.DIFICIL, new String(yytext()));
            }
          case 95: break;
          case 35: 
            { return symbol(sym.acumular);
            }
          case 96: break;
          case 36: 
            { return symbol(sym.ACCIONES);
            }
          case 97: break;
          case 37: 
            { return symbol(sym.PLANETAS);
            }
          case 98: break;
          case 38: 
            { return symbol(sym.columnas);
            }
          case 99: break;
          case 39: 
            { return symbol(sym.planetas);
            }
          case 100: break;
          case 40: 
            { return symbol(sym.IMPACTOS);
            }
          case 101: break;
          case 41: 
            { return symbol(sym.mapaCiego);
            }
          case 102: break;
          case 42: 
            { return symbol(sym.posX);
            }
          case 103: break;
          case 43: 
            { return symbol(sym.posY);
            }
          case 104: break;
          case 44: 
            { return symbol(sym.NEUTRALES);
            }
          case 105: break;
          case 45: 
            { return symbol(sym.JUGADORES);
            }
          case 106: break;
          case 46: 
            { return symbol(sym.produccion);
            }
          case 107: break;
          case 47: 
            { return symbol(sym.SECUENCIAS);
            }
          case 108: break;
          case 48: 
            { return symbol(sym.verificador);
            }
          case 109: break;
          case 49: 
            { return symbol(sym.turnoLlegada);
            }
          case 110: break;
          case 50: 
            { return symbol(sym.finalizacion);
            }
          case 111: break;
          case 51: 
            { return symbol(sym.mostrarNaves);
            }
          case 112: break;
          case 52: 
            { return symbol(sym.estadoJugador);
            }
          case 113: break;
          case 53: 
            { return symbol(sym.planetaOrigen);
            }
          case 114: break;
          case 54: 
            { return symbol(sym.navesRestantes);
            }
          case 115: break;
          case 55: 
            { return symbol(sym.noJugadorEnvio);
            }
          case 116: break;
          case 56: 
            { return symbol(sym.planetaDestino);
            }
          case 117: break;
          case 57: 
            { return symbol(sym.noJugadorAtaque);
            }
          case 118: break;
          case 58: 
            { return symbol(sym.pNeutrales);
            }
          case 119: break;
          case 59: 
            { return symbol(sym.porcMuertes);
            }
          case 120: break;
          case 60: 
            { return symbol(sym.PLANETAS_NEUTRALES);
            }
          case 121: break;
          case 61: 
            { return symbol(sym.mostrarEstadisticas);
            }
          case 122: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Converts an int token code into the name of the
   * token by reflection on the cup symbol class/interface sym
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   */
  private String getTokenName(int token) {
    try {
      java.lang.reflect.Field [] classFields = sym.class.getFields();
      for (int i = 0; i < classFields.length; i++) {
        if (classFields[i].getInt(null) == token) {
          return classFields[i].getName();
        }
      }
    } catch (Exception e) {
      e.printStackTrace(System.err);
    }

    return "UNKNOWN TOKEN";
  }

  /**
   * Same as next_token but also prints the token to standard out
   * for debugging.
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   */
  public java_cup.runtime.Symbol debug_next_token() throws java.io.IOException {
    java_cup.runtime.Symbol s = next_token();
    System.out.println( "line:" + (yyline+1) + " col:" + (yycolumn+1) + " --"+ yytext() + "--" + getTokenName(s.sym) + "--");
    return s;
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java AnalizadorLexico3 [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        AnalizadorLexico3 scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new AnalizadorLexico3(reader);
          while ( !scanner.zzAtEOF ) scanner.debug_next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
